### ISSUE TITLE
Creating tag fails

### ISSUE THREAD

**Issue by PlutoHDDev** [lucasheld/ansible-uptime-kuma#18]
I am trying to create a tag like this:
```
- name: Add Development tag
  lucasheld.uptime_kuma.tag:
    api_url: http://127.0.0.1:3001
    api_token: "{{ api_token }}"
    name: Development
    color: "#0000ff"
    state: present
```

but it fails with this error:
`FAILED! => {"changed": false, "msg": "Traceback (most recent call last):\n  File \"/tmp/ansible_lucasheld.uptime_kuma.tag_payload_esq43o_3/ansible_lucasheld.uptime_kuma.tag_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/tag.py\", line 129, in main\n  File \"/tmp/ansible_lucasheld.uptime_kuma.tag_payload_esq43o_3/ansible_lucasheld.uptime_kuma.tag_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/tag.py\", line 89, in run\nTypeError: add_tag() takes 1 positional argument but 3 were given\n"}`
