### ISSUE TITLE
Feature Request: Use API Token instead of Login/Password to be able to use the Role with activated 2FA

### ISSUE THREAD

**Issue by solick** [lucasheld/ansible-uptime-kuma#23]
Hi, thanks first for the great role.

I tried to configure my uptime kuma instance with your role and found out, that it seems not to be possible if 2FA is activated.

As far as I understand, the option to use an api-token only works with the session token one receive after use the normal login method with password. I tried to generate an API token via Web UI and use this in the ansible role but it did not work out. 

If you activate 2FA, then the above described process will not work because the  initial login with password will fail. In the uptime kuma logs the error message is: 

`[AUTH] INFO: 2FA token required for user admin. IP=127.0.0.1`

So it would be great and from security pint of view recommended to are able to use an api token generated in the web ui for ansible and activate 2FA for the Dashboard login.

**Comment by lucasheld** [comment]
Do I understand you correctly that you have created an API Key in the web interface at `Settings -> API Keys`?

If that is the case, it has already been mentioned here: https://github.com/lucasheld/uptime-kuma-api/issues/24
Unfortunately, it is currently not possible to use these API Keys in combination with the Socket.IO API endpoint. This API Key can only be used to access the Prometheus metrics endpoint. This has nothing to do with activated 2FA.

To login with activated 2FA, you have to use the `login` module with the arguments `api_username`, `api_password` and `api_2fa`. The `token` in the result can then be used for other modules.

**Comment by solick** [comment]
Hi, ok but how wold the api_2fa parameter would work if it is a One Time Password?

**Comment by lucasheld** [comment]
### Enable 2FA in Uptime Kuma
1. Enable 2FA in the webinterface at `Settings -> Security -> Two Factor Authentication`.
2. Click on `Show URI` and copy the `secret` parameter only (e.g. `IV2HCU3KNM2WUVKUNBMU4UZUMVRXARTXGZMUY23YJRZG6TTWOFYDATTRKZ4WQUDQMRNHERLQJBTVKR3BIZZTMV2MPJEHQMKZOM4VGTI`)
3. Generate a TOTP token, e.g. using the python module pyotp
    ```python
    >>> import pyotp
    >>> secret = "IV2HCU3KNM2WUVKUNBMU4UZUMVRXARTXGZMUY23YJRZG6TTWOFYDATTRKZ4WQUDQMRNHERLQJBTVKR3BIZZTMV2MPJEHQMKZOM4VGTI"
    >>> pyotp.TOTP(secret).now()
    '455117'
    ```
4. Go back to the webinterface and verify that TOTP token
5. Click `Save` and `Yes`, 2FA is enabled now

### Use the TOTP token in ansible-uptime-kuma
1. Generate a new TOTP token as the old one has probably expired
    ```python
    >>> pyotp.TOTP(secret).now()
    '781932'
    ```
2. This is an example playbook. You have to set the TOTP token as fact (e.g. `api_2fa: 781932`). The playbook uses the `login` module to generate an `api_token` that can be used with other modules (e.g. `settings_info`)
    ```yml
    ---
    - hosts: localhost
      connection: local
      tasks:
        - set_fact:
            api_url: http://127.0.0.1:3001
            api_2fa: 781932
    
        - name: Login with credentials once and register the result
          lucasheld.uptime_kuma.login:
            api_url: "{{ api_url }}"
            api_username: admin
            api_password: secret123
            api_2fa: "{{ api_2fa }}"
          register: result
    
        - name: Extract the token from the result and set it as fact
          set_fact:
            api_token: "{{ result.token }}"
    
        - name: get settings
          lucasheld.uptime_kuma.settings_info:
            api_token: "{{ api_token }}"
          register: result
    
        - name: print settings
          debug:
            var: result
    ```
