### ISSUE TITLE
`settings.entryPage` adds configured option but selection is missing

### ISSUE THREAD

**Issue by maxkratz** [lucasheld/ansible-uptime-kuma#26]
Consider the following task:
```
- name: Configure status page as entry page
  lucasheld.uptime_kuma.settings:
    api_url: https://{{ status_url }}
    api_token: "{{ api_token }}"  
    entryPage: "1uhosting"
```

The entry page "1uhosting" gets configured but the selection of the radio button within the web UI is missing:
![Screenshot from 2023-07-08 17-38-12](https://github.com/lucasheld/ansible-uptime-kuma/assets/20956405/e95835c8-4164-4add-84a0-b57d96469721)

Is there another setting available to configure this selection or is this behavior a bug?

**Comment by lucasheld** [comment]
I have added a status page with the slug `1uhosting` and then checked HTML input field of the Uptime Kuma settings. It looks like Uptime Kuma requires the prefix `statusPage-` in the entryPage value to display it correctly.
```yml
- name: Add status page
  lucasheld.uptime_kuma.status_page:
    api_url: https://{{ status_url }}
    api_token: "{{ api_token }}"
    slug: 1uhosting
    title: 1uhosting
    state: present
```

![image](https://github.com/lucasheld/ansible-uptime-kuma/assets/44499529/9a26a312-6d02-4f7f-86e4-2cf65ad47d73)

So you have to replace

```yml
- name: Configure status page as entry page
  lucasheld.uptime_kuma.settings:
    api_url: https://{{ status_url }}
    api_token: "{{ api_token }}"
    entryPage: "1uhosting"
```

with

```yml
- name: Configure status page as entry page
  lucasheld.uptime_kuma.settings:
    api_url: https://{{ status_url }}
    api_token: "{{ api_token }}"
    entryPage: "statusPage-1uhosting"
````
