### ISSUE TITLE
maintenance: TypeError: '<' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by tigattack** [lucasheld/ansible-uptime-kuma#28]
Hey, thanks for this collection and the Python library, both have been super useful for me, really appreciate the work.

I've encountered a bug with the `maintenance` module. The following task causes the error noted in the title:

```yml
- name: Set maintenance schedules
  lucasheld.uptime_kuma.maintenance:
    title: Plex Sync
    description: Plex server synchronisation
    strategy: recurring-weekday
    intervalDay: 1
    weekdays: [2, 3, 4, 5, 6, 7, 0]
    timeRange:
      - hours: 7
        minutes: 0
      - hours: 7
        minutes: 30
    monitors:
      - name: Plex Media Server
      - name: Backup Plex Media Server
  tags: maintenance
```

This seems to be caused by attempting to sort a list of dicts here: [maintenance.py#L252](https://github.com/lucasheld/ansible-uptime-kuma/blob/master/plugins/modules/maintenance.py#L252)
