### ISSUE TITLE
disableAuth: true setting not working

### ISSUE THREAD

**Issue by DatGizmo** [lucasheld/ansible-uptime-kuma#39]
To set the 'disableAuth' to true the password needs to be present.
In the python api this is done by adding the password param to the 'set_settings' call. [See uptime-api](https://github.com/lucasheld/uptime-kuma-api/issues/5#issuecomment-1258435331)

It looks like the password value is not part of set_settings call.

The way I tried to disableAuth in ansible:
``` yaml
- name: Disable auth
  lucasheld.uptime_kuma.settings:
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
    disableAuth: true
```
Following error occured:
```
The full traceback is:
  File "/tmp/ansible_lucasheld.uptime_kuma.settings_payload_fjkg8r62/ansible_lucasheld.uptime_kuma.settings_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/settings.py", line 161, in main
  File "/tmp/ansible_lucasheld.uptime_kuma.settings_payload_fjkg8r62/ansible_lucasheld.uptime_kuma.settings_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/settings.py", line 108, in run
  File "/usr/local/lib/python3.10/dist-packages/uptime_kuma_api/api.py", line 2819, in set_settings
    return self._call('setSettings', (data, password))
  File "/usr/local/lib/python3.10/dist-packages/uptime_kuma_api/api.py", line 550, in _call
    raise UptimeKumaException(r.get("msg"))
fatal: [localhost]: FAILED! => changed=false
  invocation:
    module_args:
      api_headers: null
      api_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      api_ssl_verify: true
      api_timeout: 10.0
      api_token: null
      api_url: http://localhost:3001
      api_username: admin
      api_wait_events: 0.2
      checkBeta: null
      checkUpdate: null
      chromeExecutable: null
      disableAuth: true
      dnsCache: null
      entryPage: null
      keepDataPeriodDays: null
      nscd: null
      password: null
      primaryBaseURL: null
      searchEngineIndex: null
      serverTimezone: Europe/Berlin
      steamAPIKey: null
      tlsExpiryNotifyDays: null
      trustProxy: null
  msg: |-
    Traceback (most recent call last):
      File "/tmp/ansible_lucasheld.uptime_kuma.settings_payload_fjkg8r62/ansible_lucasheld.uptime_kuma.settings_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/settings.py", line 161, in main
      File "/tmp/ansible_lucasheld.uptime_kuma.settings_payload_fjkg8r62/ansible_lucasheld.uptime_kuma.settings_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/settings.py", line 108, in run
      File "/usr/local/lib/python3.10/dist-packages/uptime_kuma_api/api.py", line 2819, in set_settings
        return self._call('setSettings', (data, password))
      File "/usr/local/lib/python3.10/dist-packages/uptime_kuma_api/api.py", line 550, in _call
        raise UptimeKumaException(r.get("msg"))
    uptime_kuma_api.exceptions.UptimeKumaException: Wrong data type?
 ```

**Comment by obfusk** [comment]
https://github.com/lucasheld/ansible-uptime-kuma/wiki/settings says:

```
password (string): The Uptime Kuma password. Only required if disableAuth is true.
```

If you're setting `disableAuth: true` you need to specify `password` as well, even if you're using `api_password` instead of `api_token`:

```yaml
- name: Disable auth
  lucasheld.uptime_kuma.settings:
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
    disableAuth: true
    password: "{{ api_password }}"
```
