### ISSUE TITLE
monitor_info - pushToken and url equals null 

### ISSUE THREAD

**Issue by yurinek** [lucasheld/ansible-uptime-kuma#5]
Hello,

we need to parse pushToken and url to use it in our scripts to push messages to a push-monitor.

```- name: Login by token and create a push monitor
  lucasheld.uptime_kuma.monitor:
    api_url: "http://{{ kuma_host }}"
    api_token: "{{ api_token }}"
    name: BackupScript
    type: push
    interval: 60
    maxretries: 0
    state: present

- name: get push monitor
  lucasheld.uptime_kuma.monitor_info:
    api_url: "http://{{ kuma_host }}"
    api_token: "{{ api_token }}"
    name: BackupScript
  register: push_monitor_result

- name: debug push_monitor_pushToken
  debug: msg="{{ push_monitor_result.pushToken }}"

- name: debug push_monitor_url
  debug: msg="{{ push_monitor_result.url }}"
```

however the above outputs Null for these return values

```TASK [kuma : debug push_monitor_url] *********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        {
            "accepted_statuscodes": [
                "200-299"
            ],
            "active": true,
            "authDomain": null,
            "authMethod": "",
            "authWorkstation": null,
            "basic_auth_pass": null,
            "basic_auth_user": null,
            "body": null,
            "databaseConnectionString": null,
            "databaseQuery": null,
            "dns_last_result": null,
            "dns_resolve_server": "1.1.1.1",
            "dns_resolve_type": "A",
            "docker_container": null,
            "docker_host": null,
            "expiryNotification": false,
            "headers": null,
            "hostname": null,
            "id": 2,
            "ignoreTls": false,
            "interval": 60,
            "keyword": null,
            "maxredirects": 10,
            "maxretries": 0,
            "method": "GET",
            "mqttPassword": null,
            "mqttSuccessMessage": null,
            "mqttTopic": null,
            "mqttUsername": null,
            "name": "BackupScript",
            "notificationIDList": [],
            "port": 53,
            "proxyId": null,
            "pushToken": null,
            "radiusCalledStationId": null,
            "radiusCallingStationId": null,
            "radiusPassword": null,
            "radiusSecret": null,
            "radiusUsername": null,
            "resendInterval": 0,
            "retryInterval": 60,
            "tags": [],
            "type": "push",
            "upsideDown": false,
            "url": null,
            "weight": 2000
        }
    ]
}```

**Comment by yurinek** [comment]
now the new issue is that none of Return Values work except "monitors" key.
e.g.

```
- name: get push monitor
  lucasheld.uptime_kuma.monitor_info:
    api_url: "http://{{ kuma_host }}"
    api_token: "{{ api_token }}"
    name: "{{ push_monitor_name }}" 
  register: push_monitor_result

- name: debug 2
  debug: msg="{{ push_monitor_result.pushToken }}"
```

with

```
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'pushToken
```

same error for other return keys except push_monitor_result.monitors

**Comment by lucasheld** [comment]
The monitor_info module returns a list of monitors. If you specifiy a monitor `name` or `id`, the list contains only one entry. Otherwise the list contains all available monitors. The list is stored in the value of the `monitors` key.

In your case, the requested monitor is the first entry in the list (index 0). You can use this entry to access the `pushToken`.

```yml
- name: add monitor
  lucasheld.uptime_kuma.monitor:
    api_url: "http://{{ kuma_host }}"
    api_token: "{{ api_token }}"
    name: BackupScript
    type: push
    interval: 60
    maxretries: 0
    state: present

- name: get push monitor
  lucasheld.uptime_kuma.monitor_info:
    api_url: "http://{{ kuma_host }}"
    api_token: "{{ api_token }}"
    name: BackupScript
  register: push_monitor_result

- set_fact:
    monitor_push_token: "{{ push_monitor_result.monitors[0].pushToken }}"

- set_fact:
    monitor_push_url: "http://{{ kuma_host }}/api/push/{{ monitor_push_token }}?status=up&msg=OK&ping="

- debug:
    var: monitor_push_token

- debug:
    var: monitor_push_url
```
