### ISSUE TITLE
lucasheld.uptime_kuma.notification Unsupported parameters telegramBotToken, telegramChatID, type

### ISSUE THREAD

**Issue by wolfi1k** [lucasheld/ansible-uptime-kuma#51]
Hi,
i am trying to setup a notification using the `lucasheld.uptime_kuma.notification` module.

Ansible version: ansible [core 2.16.2]
Uptime Kuma Ansible-Galaxy version: lucasheld.uptime_kuma         1.2.0
uptime_kuma_api Version (pip): Version: 1.2.1

I am trying the following config adopting the [example](https://github.com/lucasheld/ansible-uptime-kuma/wiki/notification) from the documentation:

```
- name: Add Telegram Notification
  lucasheld.uptime_kuma.notification:
    api_url: "{{ uptime_kuma_api_url }}"
    api_token: "{{ api_token }}"
    name: Telegram
    type: telegram
    isDefault: true
    applyExisting: true
    telegramBotToken: "{{ uptime_kuma_telegram_bot_token }}"
    telegramChatID: "{{ uptime_kuma_telegram_chat_id }}"
    state: present
```

However when i run this with Ansible i get the following error:
```
TASK [uptime-kuma : Add Telegram Notification] **************************************************************************************************************************************************
fatal: [XXX.XXX.X.XX]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (lucasheld.uptime_kuma.notification) module: telegramBotToken, telegramChatID, type. Supported parameters include: api_headers, api_password, api_ssl_verify, api_timeout, api_token, api_url, api_username, api_wait_events, applyExisting, id, isDefault, name, state (default)."}
```

It seems like the parameter is not implemented at all.
It is also only listed in the examples, but not in the documentation itself.
Is there an error in the example, my usage or are these commands simply not implemented?

Best Regards
Wolfi

**Comment by corvus-migratorius** [comment]
The exact task below worked just fine for us. Notification was created automatically as expected, and got tested successfully.

```yaml
- name: Add Telegram notifications
  lucasheld.uptime_kuma.notification:
    api_url: http://127.0.0.1:{{ kuma_port }}
    api_token: "{{ kuma_api_token }}"
    type: telegram
    name: Telegram alerts
    isDefault: true
    applyExisting: true
    telegramBotToken: "{{ kuma_tg_bot_token }}"
    telegramChatID: "{{ kuma_tg_chat_id }}"
    state: present
```

Kuma was deployed as a Docker container (`louislam/uptime-kuma`). Here is part of the deployment configuration from the same playbook:

```yaml
---
kuma_img_version: "1.23.16-alpine"
kuma_port: 3001
kuma_api_version: "1.2.0"
```
