### ISSUE TITLE
monitor_info error

### ISSUE THREAD

**Issue by yurinek** [lucasheld/ansible-uptime-kuma#6]
Hi,

we explored the following issue

```
- name: Login with credentials once and register the token
  lucasheld.uptime_kuma.login:
    api_url: "http://{{ kuma_host }}"
    api_username: "{{ gui_user }}"
    api_password: "{{ gui_password }}"
  register: token_result

- name: Extract the token from the result and set it as fact
  set_fact:
    api_token: "{{ token_result.token }}"

- name: Login by token and create a push monitor
  lucasheld.uptime_kuma.monitor:
    api_url: "http://{{ kuma_host }}"
    api_token: "{{ api_token }}"
    name: "{{ push_monitor_name }}" 
    type: push
    interval: 60
    maxretries: 0
    state: present

- name: get push monitor
  lucasheld.uptime_kuma.monitor_info:
    api_url: "http://{{ kuma_host }}"
    api_token: "{{ api_token }}"
    name: "{{ push_monitor_name }}" 
  register: push_monitor_result
```

which outputs 

```
failed: [localhost] (item=BackupScript) => {"ansible_loop_var": "item", "changed": false, "item": "BackupScript", "msg": "Traceback (most recent call last):\n  File \"/tmp/ansible_lucasheld.uptime_kuma.monitor_info_payload_a5hbmzch/ansible_lucasheld.uptime_kuma.monitor_info_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/monitor_info.py\", line 302, in main\n  File \"/tmp/ansible_lucasheld.uptime_kuma.monitor_info_payload_a5hbmzch/ansible_lucasheld.uptime_kuma.monitor_info_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/monitor_info.py\", line 268, in run\nAttributeError: 'list' object has no attribute 'items'\n"}
```
